import Head from 'next/head';
import Image from 'next/image';
import Header from '../components/Header';
import WordSearch from '../components/WordSearch';
import styles from '../styles/Home.module.css';
import { VALIDWORDS } from '../public/5-words';
import { Button, Heading, Box } from '@chakra-ui/react';
import WordList from '../components/WordList';
import { useState, useEffect } from 'react';

export default function Home() {
  const [ guesses, setGuesses ] = useState(VALIDWORDS);
  const [ inputVal, setInputVal ] = useState('-----');

  useEffect(
    () => {
      setGuesses(
        VALIDWORDS.filter((word) => {
          if (
            (word[0] === inputVal[0] || inputVal[0] === '-') &&
            (word[1] === inputVal[1] || inputVal[1] === '-') &&
            (word[2] === inputVal[2] || inputVal[2] === '-') &&
            (word[3] === inputVal[3] || inputVal[3] === '-') &&
            (word[4] === inputVal[4] || inputVal[4] === '-')
          )
            return true;
        })
      );
    },
    [ inputVal ]
  );

  const clearInput = () => {
    setInputVal('-----');
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header />
      <main className={styles.main}>
        <h1 className={styles.title}>Enter word below!</h1>

        <div>
          <div className={styles.grid}>
            <div className={styles.card}>
              <WordSearch value={inputVal} setValue={setInputVal} />
            </div>
          </div>

          <Box mt='2' display='flex' justifyContent='center'>
            <Button variant='outline' colorScheme='red' onClick={clearInput}>
              Clear
            </Button>
          </Box>
        </div>

        <p className={styles.description}>
          <Heading>matches</Heading>
        </p>

        <WordList words={guesses} setGuesses={setGuesses} />
      </main>

      <footer className={styles.footer}>
        <a href='https://google.com' target='_blank' rel='noopener noreferrer'>
          Made by jz
        </a>
      </footer>
    </div>
  );
}
